# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: e00181e313bb6f910fb5620ba46c63e56e3997dc1e0512f26448c7b9e05635236d4ffb46b37834be179850f0a91cd1edbf24330ff3c04b76300ebb2cc7e78340

test:
  secret_key_base: 49d4dcb892a67b5decc0a3ec29d6e81d6bb4796b1f9624eacadef98d550c38752eba3392e31ce7b07f5519bf70c8668eda981da879fe911503c5ab9f6d769500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
